services:
    app:
        build: .
        image: laravel-app
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        depends_on:
            - redis
            - mysql
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=
            - CACHE_DRIVER=redis
            - CACHE_STORE=redis
            - QUEUE_CONNECTION=redis
            - SESSION_DRIVER=redis
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
            - REDIS_DB=0
            - REDIS_CACHE_DB=1
        command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

    node:
        image: node:20.19.0
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        command: ["npm", "run", "dev"]
        ports:
            - "5173:5173"
        depends_on:
            - app

    redis:
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"

    mysql:
        image: mysql:8.4
        container_name: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
